### ISSUE TITLE
Why Voidy instead of java.lang.Void

### ISSUE THREAD

**Issue by rdehuyss** [sizovs/PipelinR#10]
Hi guys,

why did you introduce Voidy? java.lang.Void also exists which would fit the use case exactly.

Cheers,
R

**Comment by sizovs** [comment]
Hi @rdehuyss 

Because it's not possible to create an instance of`java.lang.Void`, a developer is forced to return null. With the current implementation, nulls are not allowed – commands always have to return something – making the code NPE-safe. 

This behavior is expected because the return type of Pipeline's execute() method is not explicitly market @Nullable.
