### ISSUE TITLE
Get notification handler name inside Notification.Middleware

### ISSUE THREAD

**Issue by arkadiuszSzast** [sizovs/PipelinR#18]
Hi,

I'm trying to get Notification.Handler class name inside Notification.Middleware but I cannot find any way to achieve that. I need it inside my 'LoggableMiddleware' and 'TraceableMiddleware'. Just for logging that name and adding it as a span tag. Is there any option to do it?

```
data class Ping(val from: String): Notification {

    @Component
    class PongHandler :Notification.Handler<Ping> {
        override fun handle(notification: Ping) {
            TODO("Not yet implemented")
        }
    }
    
    @Component
    class Pong2Handler :Notification.Handler<Ping> {
        override fun handle(notification: Ping) {
            TODO("Not yet implemented")
        }
    }
}
```

And from middleware I want to log something like "Handling Ping notification in  PongHandler "

**Comment by sizovs** [comment]
Hi Arkadiusz @arkadiuszSzast 

There is no way to achieve this with Middlewares because Middlewares don't know which Handler will be handling the Notification. This is because a Notification Handler is just another Middleware that runs after other Middlewares, and all Middlewares are independent.

If you want to know which Handlers have handled a Notification, you can achieve that by creating a base Handler class that does the logic and then derive your concrete handler from it.

Does it work for you?
