### ISSUE TITLE
"Dead Letter Queue" for Notifications

### ISSUE THREAD

**Issue by dstutz** [sizovs/PipelinR#35]
After browsing through the closed Issues I see this comment from you on "Get notification handler name inside Notification.Middleware"  (https://github.com/sizovs/PipelinR/issues/18#issuecomment-907658132):

> There is no way to achieve this with Middlewares because Middlewares don't know which Handlers will be handling the Notification. This is because a Notification Handler is just another Middleware that runs after all custom Middlewares (and all Middlewares are independent of each other).

So I'm going to assume it isn't possible to add functionality to have an unhandled notification or DLQ for notifications or is there a possibility for such feature?

**Comment by sizovs** [comment]
Hi @dstutz 

Nice to e-meet you! Please describe your use case in more detail, and we'll see if PipelinR supports it natively, and if not, how to implement it otherwise.

– Eduards

**Comment by sizovs** [comment]
@dstutz Got it! The limitation is that PipelinR doesn't know if notification is unhandled because of a misconfiguration or intentionally (e.g., because the `matches()` method in Notification.Handlers returns false due a business condition). To prevent the configuration issue you mentioned, you can create an ArchUnit rule to verify that each notification has at least one corresponding handler.

**Comment by dstutz** [comment]
Fair enough.  Thank you for the information.
